#db configuration
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver  
    url : jdbc:mysql://localhost:3306/project_blog_apis_app
    username: root
    password: Redmi@123

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate.dialect : org.hibernate.dialect.MySQL5Dialect

# Show or not log for each sql query
    show-sql: true

# Hibernate ddl auto (create, create-drop, update)
    hibernate.ddl-auto: update
